// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDffSNjsKXb4H8FqHhvyzptQjZ7BBG4IHo',
    appId: '1:618714587574:web:a97fd64ebf784b33e46117',
    messagingSenderId: '618714587574',
    projectId: 'flutter-ie',
    authDomain: 'flutter-ie.firebaseapp.com',
    storageBucket: 'flutter-ie.firebasestorage.app',
    measurementId: 'G-LFG21MY533',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHKkt6Udek_LRGq5WaAYo5dE9XrSuXkJA',
    appId: '1:618714587574:android:f5765dffb181866be46117',
    messagingSenderId: '618714587574',
    projectId: 'flutter-ie',
    storageBucket: 'flutter-ie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPnY0HQSWYL1MV1uJM2n849KkYRCBxLvc',
    appId: '1:618714587574:ios:2b54bc1d055a39d2e46117',
    messagingSenderId: '618714587574',
    projectId: 'flutter-ie',
    storageBucket: 'flutter-ie.firebasestorage.app',
    iosBundleId: 'com.example.prueba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPnY0HQSWYL1MV1uJM2n849KkYRCBxLvc',
    appId: '1:618714587574:ios:2b54bc1d055a39d2e46117',
    messagingSenderId: '618714587574',
    projectId: 'flutter-ie',
    storageBucket: 'flutter-ie.firebasestorage.app',
    iosBundleId: 'com.example.prueba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDffSNjsKXb4H8FqHhvyzptQjZ7BBG4IHo',
    appId: '1:618714587574:web:f847ca01718e77b0e46117',
    messagingSenderId: '618714587574',
    projectId: 'flutter-ie',
    authDomain: 'flutter-ie.firebaseapp.com',
    storageBucket: 'flutter-ie.firebasestorage.app',
    measurementId: 'G-KHEC823C1F',
  );
}
